{% set name = "holidays" %}
{% set version = "0.59" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c5cd2e1c0c27a64217b10faf2e8fcc224f5bb64087b56b70c6aff21f6379e6e4

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8
    - pip
    - setuptools
  run:
    - python >=3.8
    - python-dateutil

test:
  imports:
    - holidays
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/vacanza/python-holidays/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Generate and work with holidays in Python
  description: |
    A fast, efficient Python library for generating country, province and state
    specific sets of holidays on the fly. It aims to make determining whether a
    specific date is a holiday as fast and flexible as possible.
  dev_url: https://github.com/vacanza/python-holidays/
  doc_url: https://python-holidays.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - bletham
    - rpanai
    - synapticarbors
