{% set name = "holidays" %}
{% set version = "0.64" %}
{% set python_min = "3.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c9ebd1b0391700cadeb4fab88274833ee7f1f355966e0486068ec0816122d26a

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - python-dateutil

test:
  imports:
    - holidays
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: https://github.com/vacanza/python-holidays/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Generate and work with holidays in Python
  description: |
    A fast, efficient Python library for generating country, province and state
    specific sets of holidays on the fly. It aims to make determining whether a
    specific date is a holiday as fast and flexible as possible.
  dev_url: https://github.com/vacanza/python-holidays/
  doc_url: https://python-holidays.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - bletham
    - rpanai
    - synapticarbors
