{% set name = "holidays" %}
{% set version = "0.15" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: bdf46c8ae2ef18ef5b3a80e0a18f8e2d5c43c34756eac8930c628dc48d51de0e

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - python-dateutil
    - convertdate >=2.3.0
    - korean_lunar_calendar
    - hijri-converter

test:
  imports:
    - holidays

about:
  home: https://github.com/dr-prodigy/python-holidays
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Generate and work with holidays in Python
  description: |
    A fast, efficient Python library for generating country, province and state
    specific sets of holidays on the fly. It aims to make determining whether a
    specific date is a holiday as fast and flexible as possible.

extra:
  recipe-maintainers:
    - bletham
    - rpanai
    - synapticarbors
