{% set name = "holidays" %}
{% set version = "0.18" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e94d9d3536ff1a2a70d6d2f56cb055eb9a95d0b9a3a5fb81b9e8f9d36e333789

build:
  skip: True     # [py<37]
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python
    - python-dateutil
    - convertdate >=2.3.0
    - korean_lunar_calendar
    - hijri-converter

test:
  imports:
    - holidays
  requires:
    # due to conda build bug which causes python 3.10 to be used
    - python <3.10
    - pip
  commands:
    - pip check

about:
  home: https://github.com/dr-prodigy/python-holidays
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Generate and work with holidays in Python
  description: |
    A fast, efficient Python library for generating country, province and state
    specific sets of holidays on the fly. It aims to make determining whether a
    specific date is a holiday as fast and flexible as possible.
  dev_url: https://github.com/dr-prodigy/python-holidays
  doc_url: https://pypi.org/project/holidays/

extra:
  recipe-maintainers:
    - bletham
    - rpanai
    - synapticarbors
